plugins {
    id 'idea'
    id 'java'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.78'
    id 'com.diffplug.spotless' version '8.9.0'
}

version = mod_version
group = mod_group_id

repositories {
    mavenCentral()
    ivy {
        setUrl('https://download.nodecdn.net/containers/reforged/universal/release')

        metadataSources {
            artifact()
            gradleMetadata()
        }
        patternLayout {
            artifact('[artifact].[ext]')
        }
    }
}

base {
    archivesName = mod_id
}

tasks.withType(Jar).configureEach {
    archiveFileName = "${mod_name}-${mod_platform}-${minecraft_version}-${mod_version}.jar"
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neo_version
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    implementation("pixelmon:Pixelmon-${minecraft_version}-${pixelmon_version}-universal:${pixelmon_version}")
    implementation 'org.xerial:sqlite-jdbc:3.46.1.3'
    jarJar 'org.xerial:sqlite-jdbc:3.46.1.3'
    implementation 'com.zaxxer:HikariCP:5.1.0'
    jarJar 'com.zaxxer:HikariCP:5.1.0'
    interfaceInjectionData("pixelmon:Pixelmon-${minecraft_version}-${pixelmon_version}-universal-interfaceinjection:${pixelmon_version}@json")
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neo_version            : neo_version,
            neo_version_range      : neo_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            pixelmon_version       : pixelmon_version
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

// IDEA no longer automatically downloads sources/javadoc jars for dependencies, so we need to explicitly enable the behavior.
idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}

spotless {
  java {

    removeUnusedImports()
    forbidWildcardImports()
    forbidModuleImports()

    cleanthat()

    palantirJavaFormat()
    
    importOrder('', '\\n', 'java|javax', '\\n', 'net.neoforged', '\\n', 'net.minecraft', '\\n', 'com.pixelmonmod', '\\n', '\\#')

  }
}