org.gradle.jvmargs=-Xmx4g
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configureondemand=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.200
neo_version_range=[21.1.0,)
loader_version_range=[4,)
pixelmon_version=9.3.16

mod_group_id=com.pokelogger
mod_id=pokelogger
mod_platform=Neoforge
mod_name=Pokelogger
mod_license=CUSTOM
mod_version=1.0.0
mod_authors=[Kre0lidge,Diablo]
mod_description=CoreProtect-style logging & lookup for Pixelmon events: trades, gifts, deletions, captures, evolutions, held items.